import '../constants/api_endpoints.dart';

class ApiException implements Exception { ApiException(this.message,{this.statusCode,this.payload}); final String message; final int? statusCode; final dynamic payload; @override String toString()=>message; }
class MediaModel{const MediaModel({this.id,this.url,this.thumbnailUrl,this.filename,this.mimeType,this.alt});final String? id,url,thumbnailUrl,filename,mimeType,alt;String? get absoluteUrl{final u=url??thumbnailUrl;if(u==null||u.isEmpty)return null;if(u.startsWith('http'))return u;return '${ApiEndpoints.baseUrl}$u';}factory MediaModel.fromJson(dynamic j)=>j is Map<String,dynamic>?MediaModel(id:j['id']?.toString(),url:j['url']?.toString(),thumbnailUrl:j['thumbnailURL']?.toString(),filename:j['filename']?.toString(),mimeType:j['mimeType']?.toString(),alt:j['alt']?.toString()):const MediaModel();}
class UserModel{const UserModel({this.id,this.email,this.name,this.role,this.pictureUrl});final String? id,email,name,role,pictureUrl;factory UserModel.fromJson(dynamic j)=>j is Map<String,dynamic>?UserModel(id:j['id']?.toString(),email:j['email']?.toString(),name:j['name']?.toString(),role:j['role']?.toString(),pictureUrl:j['socialMediaPictureUrl']?.toString()):const UserModel();}
class AuthSession{const AuthSession({this.message,this.exp,this.token,this.user});final String? message,token;final int? exp;final UserModel? user;factory AuthSession.fromJson(dynamic j)=>j is Map<String,dynamic>?AuthSession(message:j['message']?.toString(),exp:j['exp'] is int?j['exp']:int.tryParse('${j['exp']}'),token:j['token']?.toString(),user:UserModel.fromJson(j['user'])):const AuthSession();}
class OnboardInfo{const OnboardInfo({this.age='',this.country='',this.purpose='',this.goalTime=0,this.userSource='',this.languageStrength=''});final String age,country,purpose,userSource,languageStrength;final int goalTime;Map<String,dynamic> toJson()=>{'age':age,'country':country,'purpose':purpose,'goalTime':goalTime,'userSource':userSource,'languageStrength':languageStrength};factory OnboardInfo.fromJson(dynamic j)=>j is Map<String,dynamic>?OnboardInfo(age:j['age']?.toString()??'',country:j['country']?.toString()??'',purpose:j['purpose']?.toString()??'',goalTime:j['goalTime'] is int?j['goalTime']:int.tryParse('${j['goalTime']}')??0,userSource:j['userSource']?.toString()??'',languageStrength:j['languageStrength']?.toString()??''):const OnboardInfo();}
class ProgressModel{const ProgressModel({this.levelOrder=1,this.unitOrder=1,this.taskOrder=1,this.lessonOrder=1,this.achievement=''});final int levelOrder,unitOrder,taskOrder,lessonOrder;final String achievement;factory ProgressModel.fromJson(dynamic j){if(j is! Map<String,dynamic>)return const ProgressModel();int v(String k,[int d=1])=>j[k] is int?j[k]:int.tryParse('${j[k]}')??d;return ProgressModel(levelOrder:v('levelOrder'),unitOrder:v('unitOrder'),taskOrder:v('taskOrder'),lessonOrder:v('lessonOrder'),achievement:j['achievement']?.toString()??'');}}
class GamificationStock{const GamificationStock({this.palmStock=0,this.dateStock=0,this.injazStock=0});final int palmStock,dateStock,injazStock;factory GamificationStock.fromJson(dynamic j){if(j is! Map<String,dynamic>)return const GamificationStock();int v(dynamic x)=>x is int?x:int.tryParse('$x')??0;final p=j['palm'];return GamificationStock(palmStock:p is Map?v(p['palmStock']):v(j['palmStock']),dateStock:v(j['dateStock']),injazStock:v(j['injazStock']));}}
class UserProfileModel{const UserProfileModel({this.id,this.fullName,this.contactNumber,this.profilePicture,this.onboardInfo=const OnboardInfo(),this.currentProgress=const ProgressModel(),this.stock=const GamificationStock()});final String? id,fullName,contactNumber;final MediaModel? profilePicture;final OnboardInfo onboardInfo;final ProgressModel currentProgress;final GamificationStock stock;factory UserProfileModel.fromJson(dynamic j){if(j is Map<String,dynamic>&&j['docs'] is List&&(j['docs'] as List).isNotEmpty)j=(j['docs'] as List).first;if(j is Map<String,dynamic>&&j['profile'] is Map<String,dynamic>)j=j['profile'];if(j is! Map<String,dynamic>)return const UserProfileModel();return UserProfileModel(id:j['id']?.toString(),fullName:j['fullName']?.toString(),contactNumber:j['contactNumber']?.toString(),profilePicture:MediaModel.fromJson(j['profilePicture']),onboardInfo:OnboardInfo.fromJson(j['onboardInfo']),currentProgress:ProgressModel.fromJson(j['currentProgress']),stock:GamificationStock.fromJson(j['gamificationStock']));}}
class JourneyLevel{const JourneyLevel({required this.id,required this.title,required this.levelOrder,required this.units,this.active=false});final String id,title;final int levelOrder;final bool active;final List<JourneyUnit> units;factory JourneyLevel.fromJson(dynamic j)=>JourneyLevel(id:j['id']?.toString()??'',title:j['title']?.toString()??'Level',levelOrder:j['levelOrder'] is int?j['levelOrder']:int.tryParse('${j['levelOrder']}')??0,active:j['inProgressOrCompleted']==true,units:((j['units'] as List?)??[]).map((e)=>JourneyUnit.fromJson(e)).toList());}
class JourneyUnit{const JourneyUnit({required this.id,required this.title,required this.unitOrder,required this.tasks,this.active=false});final String id,title;final int unitOrder;final bool active;final List<JourneyTask> tasks;factory JourneyUnit.fromJson(dynamic j)=>JourneyUnit(id:j['id']?.toString()??'',title:j['title']?.toString()??'Unit',unitOrder:j['unitOrder'] is int?j['unitOrder']:int.tryParse('${j['unitOrder']}')??0,active:j['inProgressOrCompleted']==true,tasks:((j['tasks'] as List?)??[]).map((e)=>JourneyTask.fromJson(e)).toList());}
class JourneyTask{const JourneyTask({required this.id,required this.title,required this.taskOrder,this.lessonCount=0,this.giftBox=false,this.active=false});final String id,title;final int taskOrder,lessonCount;final bool giftBox,active;factory JourneyTask.fromJson(dynamic j)=>JourneyTask(id:j['id']?.toString()??'',title:j['title']?.toString()??'Task',taskOrder:j['taskOrder'] is int?j['taskOrder']:int.tryParse('${j['taskOrder']}')??0,lessonCount:j['lessonCount'] is int?j['lessonCount']:int.tryParse('${j['lessonCount']}')??0,giftBox:j['giftBox']==true,active:j['inProgressOrCompleted']==true);}
class LessonModel{const LessonModel({required this.id,required this.title,this.levelOrder=1,this.unitOrder=1,this.taskOrder=1,this.lessonOrder=1,this.isExam=false,this.active=false});final String id,title;final int levelOrder,unitOrder,taskOrder,lessonOrder;final bool isExam,active;factory LessonModel.fromJson(dynamic j){int v(String k)=>j[k] is int?j[k]:int.tryParse('${j[k]}')??1;return LessonModel(id:j['id']?.toString()??'',title:j['title']?.toString()??'Lesson',levelOrder:v('levelOrder'),unitOrder:v('unitOrder'),taskOrder:v('taskOrder'),lessonOrder:v('lessonOrder'),isExam:j['isExam']==true,active:j['inProgressOrCompleted']==true);}}
class AnswerModel{const AnswerModel({required this.id,this.title='',this.isCorrect,this.mediaType,this.media});final String id,title;final bool? isCorrect;final String? mediaType;final MediaModel? media;factory AnswerModel.fromJson(dynamic j)=>AnswerModel(id:j['id']?.toString()??'',title:j['title']?.toString()??'',isCorrect:j['is_correct'] is bool?j['is_correct']:null,mediaType:j['media_type']?.toString(),media:MediaModel.fromJson(j['media']));}
class QuestionModel{const QuestionModel({required this.id,required this.type,required this.title,required this.answers,this.media=const[]});final String id,type,title;final List<AnswerModel> answers;final List<MediaModel> media;factory QuestionModel.fromJson(dynamic j)=>QuestionModel(id:j['id']?.toString()??'',type:j['question_type']?.toString()??'mcq',title:j['question_title']?.toString()??'Question',answers:((j['answers'] as List?)??[]).map((e)=>AnswerModel.fromJson(e)).toList(),media:((j['questionMedia'] as List?)??[]).map((e)=>MediaModel.fromJson(e is Map?e['media']:null)).toList());}
class QuestStatus{const QuestStatus({required this.challengeId,required this.status,this.required=0,this.current=0,this.reward=0});final String challengeId,status;final int required,current,reward;factory QuestStatus.fromJson(dynamic j){final d=j['details'] is Map?j['details']:const{};int v(dynamic x)=>x is int?x:int.tryParse('$x')??0;return QuestStatus(challengeId:j['challengeId']?.toString()??'',status:j['status']?.toString()??'pending',required:v(d['required']),current:v(d['current']),reward:v(d['reward']));}}
class StreakModel{const StreakModel({this.currentStreak=0,this.missedDays=0,this.startDate,this.lastCompletedDate});final int currentStreak,missedDays;final String? startDate,lastCompletedDate;factory StreakModel.fromJson(dynamic j){if(j is! Map<String,dynamic>)return const StreakModel();int v(String k)=>j[k] is int?j[k]:int.tryParse('${j[k]}')??0;return StreakModel(currentStreak:v('currentStreak'),missedDays:v('missedDays'),startDate:j['startDate']?.toString(),lastCompletedDate:j['lastCompletedDate']?.toString());}}
class AchievementModel{const AchievementModel({required this.id,required this.title,required this.achievementTitle,this.achieved=false,this.levelOrder=0,this.unitOrder=0});final String id,title,achievementTitle;final bool achieved;final int levelOrder,unitOrder;factory AchievementModel.fromJson(dynamic j)=>AchievementModel(id:j['id']?.toString()??'',title:j['title']?.toString()??'',achievementTitle:j['achievementTitle']?.toString()??'',achieved:j['achieved']==true,levelOrder:j['levelOrder'] is int?j['levelOrder']:int.tryParse('${j['levelOrder']}')??0,unitOrder:j['unitOrder'] is int?j['unitOrder']:int.tryParse('${j['unitOrder']}')??0);}
class FaqModel{const FaqModel({required this.question,required this.answer});final String question,answer;factory FaqModel.fromJson(dynamic j)=>FaqModel(question:j['question']?.toString()??'',answer:j['answer']?.toString()??'');}
class TextBlock{static String extract(dynamic value){final parts=<String>[];void walk(dynamic n){if(n is Map){if(n['text']!=null)parts.add(n['text'].toString());for(final v in n.values){walk(v);}}else if(n is List){for(final v in n){walk(v);}}}walk(value);return parts.join('\n').trim();}}
class OnboardingOptions{const OnboardingOptions({this.purpose=const[],this.goal=const[],this.country=const[],this.userSource=const[],this.languageStrength=const[],this.age=const[],this.interests=const[]});final List<String> purpose,goal,country,userSource,languageStrength,age,interests;static List<String> _l(dynamic v)=>((v as List?)??[]).map((e)=>e is Map?(e['label']??e['title']??e['value']??e['name']).toString():e.toString()).where((e)=>e!='null').toList();factory OnboardingOptions.fromJson(dynamic j)=>OnboardingOptions(purpose:_l(j['purpose']),goal:_l(j['Goal']??j['goal']),country:_l(j['Country']??j['country']),userSource:_l(j['userSource']),languageStrength:_l(j['languageStrength']),age:_l(j['age']),interests:_l(j['interests']));}
